name: release
on:
  push:
    tags: ["v*"]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            data_sep: ":"
            exe_suffix: ""
          - os: macos-latest
            data_sep: ":"
            exe_suffix: ""
          - os: windows-latest
            data_sep: ";"
            exe_suffix: ".exe"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -U pip wheel
      - run: pip install -r requirements.txt pyinstaller
      - name: Build
        run: |
          pyinstaller --onefile --name VetteBee-Comms --add-data "config.toml${{ matrix.data_sep }}." beevette.py
      - uses: actions/upload-artifact@v4
        with:
          name: VetteBee-Comms-${{ runner.os }}
          path: dist/VetteBee-Comms${{ matrix.exe_suffix }}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
